add txt
andrewyakonyuk/expert-journey pull request #4
Opened 2017-01-20 16:33 UTC by prodigy3452

dsf

2017-01-20 19:40 UTC, andrewyakonyuk requested changes
Пару пунктов на доработку

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Views/Home/Article.cshtml
> +    <a href="http://localhost:57821/Home/EditArticle?Id=@Model.Id">EDIT</a>
Используй UrlHelper. Для примера: Url.Action("EditArticle", "Home", new { id = Model.Id })

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Views/Home/Article.cshtml
> +    <div class="publicate_time">@Html.Raw(createmsg)</div>
Крайне хреново. 
Для этого есть форматирование дат. 
[Статья в тему](http://metanit.com/sharp/tutorial/19.2.php)

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Views/Home/CreateArticle.cshtml
> +    </div>
Почти классно, но в этом случае можно сделать проще:
Html.EditorForModel() - он создаст весь html, основываясь на аттрибутах(required, display etc).
Например
`@using (Html.BeginForm("CreateArticle", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    Html.EditorForModel()
}
`

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Attributes/ValidImage.cs
> +            int maxContent = 5 * 1024 * 1024; //3 MB
Использование аттрибута для валидации одобряю.

Теперь о плохом:
1. `5 * 1024 * 1024` это ниразу не 3mb. Коммент говно. И другие такие же поудаляй
2. Максимальный размер файла захардкожен. Поэтому, нужно позволить считывать его, например, из свойства MaxFileSize. В таком случае, если тебе понадобится провалидировать размер фото, тебе не нужно менять сам аттрибут. 
3. Реальный максимальный размер файла, который можно загрузить на сервер, на самом деле деле [конфигурируется отдельно в web.config](http://stackoverflow.com/questions/288612/how-to-increase-the-max-upload-file-size-in-asp-net). 
4. Это аттрибут делает слишком много: он валидирует и размер файла, и его тип. Разбей на два отдельный. 
5. Размер файла в аттрибуте и в яваскрипте забиты отдельно и ни как не связаны. К примеру, если нужно поменять с 3(?)мб до 100, тебе прийдется искать все места, где он используется.
6. И вообще, используй [jquery unobtrusive validation](http://stackoverflow.com/questions/11534910/what-is-jquery-unobtrusive-validation), [на русском](https://habrahabr.ru/post/180279/)

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Attributes/ValidImageEditArticle.cs
> +    public class ValidImageEditArticle : ValidationAttribute
Зачем два одинаковый аттрибута?

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Controllers/HomeController.cs
> +                baseArticle.Image = edited.Image.FileName;
Использование `ConfigurationManager` одобряю.

Имеет смысл использовать путь к папке с картинками только в `FileHelper`.
`ConfigurationManager.AppSettings["UserImagesFolder"].ToString()` - ToString() не нужен

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Controllers/HomeController.cs
> +                baseArticle.FullDescription = edited.FullDescription;
проверки вида `edited.FullDescription != null` не нужны. Для этого уже есть валидационные аттрибуты.

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Controllers/HomeController.cs
> +        public ActionResult GetNewPageOfArticles(int Page)
параметры методов и переменный всегда начинаются с маленькой буквы.
Смотри в [naming guidelines](http://stackoverflow.com/a/8497191)

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/Article.cs
> +        public virtual string LastUpdateDate { get; set; }
Даты остаются с типом `DateTime`. Так что вертай как было.
Для форматирования есть другие средства + есть такая штука, как локализация, то бишь не для всех языков порядок день-месяц-год один и тот же. В Америке принят  месяц-день-год. Учитывай это

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/Article.cs
> +            Title = a.Title;
Обьект, который сохраняется в базу, ничего не должен знать об обьектах, которые используются для отображения. Это как минимум потому, что у тебя может быть одна база, но несколько приложений, которые ее используют (к примеру веб и mobile apps).
Гугли [трехуровневую архитектуру](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D1%91%D1%85%D1%83%D1%80%D0%BE%D0%B2%D0%BD%D0%B5%D0%B2%D0%B0%D1%8F_%D0%B0%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0)

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
> +        int SaveOrUpdate(CreateArticleModel model);
Как по мне, так просто `Save` намного лучше смотрится, так как он и предролагает и создание, и обновление.

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
> +                    if (a.CreateDate == null)
Вернуть тип `DateTime`. Тогда проверка будет выглядеть `if(a.CreateDate == DateTime.MinValue)`

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
> +            Article a = new Article();
[Репозиторий](http://metanit.com/sharp/articles/mvc/11.php) ничего не должен знать о таких моделях. Он работает только с `Article`

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
>          {
В этом методе не хватает `results.TotalCount = session.QueryOver<Article>().Select(Projections.RowCount()).FutureValue<int>().Value;`. 
Одинаковые вещи должны работать одинаково.

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
> +        public string GetDemoListJson(int startFrom, int count)
Методу здесь не место. Перенеси его в контроллер. Репозиторий только сохраняет и выполняет выборку данных.

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/IRepository.cs
>          public int GetCountOfLines()
Его можно уже удалить

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Controllers/HomeController.cs
> +        public ActionResult GetNPagesOfArticles(int n)
В чем принципиальная разница между `GetNPagesOfArticles` и `GetNewPageOfArticles`?
Соединить в один метод.
Даже больше: тебе ну нужен отдельный метод для рендеринга новостей и для lazy loading. Можно обойтись одним методом:
```
public ActionResult Index(int page = 0)
{
        var list = repo.GetDemoList(page, NumberOfItemsOnPage);
        if (Request.IsAjaxRequest())
        {
            return Json(list);
        }
        var model = new ListItemPageModel(NumberOfItemsOnPage, list);
        return View(model);
}
```

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Models/ViewModel/ListItemPageModel.cs
> +        public ListItemPageModel(int NumberOfItemsOnPage, PagedList<DemoArticle> ArticleList)
Имена, блеать!

2017-01-20 19:40 UTC, andrewyakonyuk commented on NewsWebSite/Views/Home/CreateArticle.cshtml
> +            var arrInputs = $("input[for='Image']").val();
скрипт говно. гугли jquery validation

2017-01-21 17:52 UTC, prodigy3452 commented on NewsWebSite/Controllers/HomeController.cs
> +                baseArticle.FullDescription = edited.FullDescription;
задумка в том, что если юзер оставит пустое поле, то значение останется старое и ошибки не будет, в атрибутах для editArticle нету [required] полей, и они пропускают null'ы

2017-01-21 17:57 UTC, prodigy3452 commented
не все учел...

2017-01-21 18:15 UTC, prodigy3452 commented on NewsWebSite/Views/Home/Article.cshtml
> +    <a href="http://localhost:57821/Home/EditArticle?Id=@Model.Id">EDIT</a>
да, я юзаю его обычно, но у меня браузер видит его как home/home/SomeMethod.. 
поэтому так написал

2017-01-21 18:49 UTC, prodigy3452 commented
не получается вернуть json(return Json(lst)), jquery выдает ошибку что не может его прочитать на 1 символе, хотя в консольке хрома он показывается как нормльный json обьект.
Минус метода который я использую в том, что он позвращает дату как строку, и ее форматировать сложно

2017-01-21 20:08 UTC, prodigy3452 commented on NewsWebSite/Views/Home/CreateArticle.cshtml
> +    </div>
да, я знаю про такую штуку, но если делать так, то для файла оно неправильный инпут создает, а так есть возможность дописать new {type = "file"} и оно все нормально отображает

2017-01-22 22:37 UTC, andrewyakonyuk requested changes

2017-01-22 22:37 UTC, andrewyakonyuk commented on NewsWebSite/Models/Repository/IRepository.cs
> +    //public class NHibernateRepository : IRepository
удали весь этот коммент

2017-01-22 22:37 UTC, andrewyakonyuk commented on NewsWebSite/Web.config
>      <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-NewsWebSite-20170115063838.mdf;Initial Catalog=aspnet-NewsWebSite-201701
и это тоже удали

2017-01-22 22:37 UTC, andrewyakonyuk commented on NewsWebSite/Web.config
> +        Server=DIMAS\SQLEXPRESS; database=NewsWebSiteDB; Integrated Security=False; User Id=root; Password=root; MultipleActiveResultSets=True;
это `Server=DIMAS\SQLEXPRESS` будет работать только на твоем ноуте. Замени на ` Server=.\SQLEXPRESS`

2017-01-22 22:44 UTC, andrewyakonyuk approved these changes

2017-01-22 22:45 UTC, merged